const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying QuizLens with account:", deployer.address);
  console.log("Balance:", ethers.formatEther(await ethers.provider.getBalance(deployer.address)), "ETH");

  const Factory = await ethers.getContractFactory("QuizLens");
  const contract = await Factory.deploy();
  await contract.waitForDeployment();

  const address = await contract.getAddress();
  console.log("\n✅ QuizLens deployed to:", address);

  // Write address to frontend config
  const config = `// Auto-generated by deploy.js — do not edit manually\nconst CONTRACT_ADDRESS = "${address}";\n`;
  const outPath = path.join(__dirname, "../frontend/contract_address.js");
  fs.writeFileSync(outPath, config);
  console.log("✅ Address written to frontend/contract_address.js");
  console.log("\nNext: open frontend/index.html in your browser and connect MetaMask.");
}

main().catch((e) => { console.error(e); process.exit(1); });